apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdk-backend
  namespace: tdk-soft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdk-site
  template:
    metadata:
      labels:
        app: tdk-site
    spec:
      containers:
      - name: backend # Ce nom doit correspondre à celui dans le 'set image'
        image: python:3.10-slim # Image temporaire, remplacée par le CI
        ports:
        - containerPort: 8000