apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdk-ingress
  namespace: tdk-soft
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: v34924.1blu.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tdk-service
            port:
              number: 80