apiVersion: v1
kind: Service
metadata:
  name: tdk-service
  namespace: tdk-soft
spec:
  selector:
    app: tdk-site
  ports:
    - protocol: TCP
      port: 80         # Port exposé au sein du cluster
      targetPort: 8000 # Port sur lequel écoute ton FastAPI (Dockerfile)
  type: ClusterIP